services:
    # Form types
    
    mu_board_module.form.type.categoryquicknav:
        class: MU\BoardModule\Form\Type\QuickNavigation\CategoryQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.forumquicknav:
        class: MU\BoardModule\Form\Type\QuickNavigation\ForumQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.postingquicknav:
        class: MU\BoardModule\Form\Type\QuickNavigation\PostingQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.aboquicknav:
        class: MU\BoardModule\Form\Type\QuickNavigation\AboQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.userquicknav:
        class: MU\BoardModule\Form\Type\QuickNavigation\UserQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.rankquicknav:
        class: MU\BoardModule\Form\Type\QuickNavigation\RankQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.handler.category:
        class: MU\BoardModule\Form\Handler\Category\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.controller_helper"
            - "@mu_board_module.model_helper"
            - "@mu_board_module.workflow_helper"
            - "@mu_board_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.category:
        class: MU\BoardModule\Form\Type\CategoryType
        arguments:
            - "@translator.default"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.collection_filter_helper"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.handler.forum:
        class: MU\BoardModule\Form\Handler\Forum\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.controller_helper"
            - "@mu_board_module.model_helper"
            - "@mu_board_module.workflow_helper"
            - "@mu_board_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.forum:
        class: MU\BoardModule\Form\Type\ForumType
        arguments:
            - "@translator.default"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.collection_filter_helper"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.handler.posting:
        class: MU\BoardModule\Form\Handler\Posting\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.controller_helper"
            - "@mu_board_module.model_helper"
            - "@mu_board_module.workflow_helper"
            - "@mu_board_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.posting:
        class: MU\BoardModule\Form\Type\PostingType
        arguments:
            - "@translator.default"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.collection_filter_helper"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
            - "@request_stack"
        tags:
            - { name: form.type }
    
    mu_board_module.form.handler.abo:
        class: MU\BoardModule\Form\Handler\Abo\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.controller_helper"
            - "@mu_board_module.model_helper"
            - "@mu_board_module.workflow_helper"
            - "@mu_board_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.abo:
        class: MU\BoardModule\Form\Type\AboType
        arguments:
            - "@translator.default"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.handler.user:
        class: MU\BoardModule\Form\Handler\User\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.controller_helper"
            - "@mu_board_module.model_helper"
            - "@mu_board_module.workflow_helper"
            - "@mu_board_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.user:
        class: MU\BoardModule\Form\Type\UserType
        arguments:
            - "@translator.default"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.collection_filter_helper"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.handler.rank:
        class: MU\BoardModule\Form\Handler\Rank\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.controller_helper"
            - "@mu_board_module.model_helper"
            - "@mu_board_module.workflow_helper"
            - "@mu_board_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.rank:
        class: MU\BoardModule\Form\Type\RankType
        arguments:
            - "@translator.default"
            - "@mu_board_module.entity_factory"
            - "@mu_board_module.collection_filter_helper"
            - "@mu_board_module.entity_display_helper"
            - "@mu_board_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.block.itemlist:
        class: MU\BoardModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.categoryfinder:
        class: MU\BoardModule\Form\Type\Finder\CategoryFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.forumfinder:
        class: MU\BoardModule\Form\Type\Finder\ForumFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.postingfinder:
        class: MU\BoardModule\Form\Type\Finder\PostingFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.abofinder:
        class: MU\BoardModule\Form\Type\Finder\AboFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.userfinder:
        class: MU\BoardModule\Form\Type\Finder\UserFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.rankfinder:
        class: MU\BoardModule\Form\Type\Finder\RankFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_board_module.form.type.config:
        class: MU\BoardModule\Form\Type\ConfigType
        arguments:
            - "@translator.default"
            - "@mu_board_module.listentries_helper"
        tags: ['form.type']
